version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${Showme}
      POSTGRES_PASSWORD: ${RaiwK_2024}
      POSTGRES_DB: ${MSA}
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  chatwoot:
    image: chatwoot/chatwoot:latest
    environment:
      RAILS_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${Showme}
      POSTGRES_PASSWORD: ${RaiwK_2024}
      POSTGRES_DB: ${MSA}
      REDIS_URL: redis://default:WwIunHpyXOvlZhCJzTneCBeMLaICWNfj@redis.railway.internal:6379
      # otras variables de entorno necesarias
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
