version: '3'

services:
  base: 
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.base
      args:
        VARIANT: "ubuntu-22.04"
        NODE_VERSION: "20.9.0"
        RUBY_VERSION: "3.3.3"
        USER_UID: "1000"
        USER_GID: "1000"
    image: base:latest

  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: chatwoot
      POSTGRES_PASSWORD: your_postgres_password_here

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: your_redis_password_here

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "ubuntu-22.04"
        NODE_VERSION: "20.9.0"
        RUBY_VERSION: "3.3.3"
    volumes:
      - ..:/workspace:cached
    environment:
      DATABASE_URL: postgres://postgres:your_postgres_password_here@db:5432/chatwoot
      REDIS_URL: redis://:your_redis_password_here@redis:6379/0
      RAILS_ENV: production
      SECRET_KEY_BASE: your_secret_key_base_here
    depends_on:
      - db
      - redis
      - mailhog
    ports:
      - "3000:3000"
    command: bundle exec rails s -b 0.0.0.0 -p 3000

  worker:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "ubuntu-22.04"
        NODE_VERSION: "20.9.0"
        RUBY_VERSION: "3.3.3"
    volumes:
      - ..:/workspace:cached
    environment:
      DATABASE_URL: postgres://postgres:RaiwK_2024@db:5432/chatwoot
      REDIS_URL: redis://:RaiwK_24@redis:6379/0
      RAILS_ENV: production
      SECRET_KEY_BASE: 6ElTwwYDiosGN0seuO871r3YvZMXBtUihULJOnpAen6VhCG48ZGqMgaodBZSowkm
    depends_on:
      - db
      - redis
      - mailhog
    command: bundle exec sidekiq

volumes:
  postgres-data:
  redis-data:
